version: '3'
services:
  ssh-gateway:
    image: ghcr.io/cgsdev0/rollycubes-ssh-gateway
    restart: always
    volumes:
      - ../secrets/:/secrets
    ports:
      - "22:3022"

networks:
  default:
    name: rollycubes
    external: true
